/*ALBERTO MORENO CARRERO - BASE DE DATOS - 1º ASIR*/

/*PREGUNTA 1*/

CREATE TABLE AMCISLAS (
   CODIGO_ISL NUMBER(3) CONSTRAINT PK_ISL PRIMARY KEY,
   NOMBRE_ISL VARCHAR2(30),
   EXTENSION NUMBER(5) CONSTRAINT EXT_ISL CHECK (EXTENSION BETWEEN 5000 AND 10000)
);

CREATE TABLE AMCPIRATAS (
   CODIGO_PIR NUMBER(3) CONSTRAINT PK_PIRATAS PRIMARY KEY,
   NOMBRE_PIR VARCHAR2(30),
   APELLIDO_PIR VARCHAR2(30),
   FECHA_NAC DATE,
   CODIGO_ISL NUMBER(3) CONSTRAINT FK_PIR_ISL REFERENCES AMCISLAS
);

CREATE TABLE AMCBARCOS (
   CODIGO_BAR NUMBER(3) CONSTRAINT PK_BARCO PRIMARY KEY,
   NOMBRE_BAR VARCHAR2(40),
   TAMANO_BAR NUMBER(5),
   TIPO_BAR VARCHAR2(20) CONSTRAINT TIPO_IN CHECK (TIPO_BAR IN('Goleta', 'Fragata'))
);

CREATE TABLE AMCASALTAN (
   CODIGO_PIR NUMBER(3) CONSTRAINT FK_ASAL_PIR REFERENCES AMCPIRATAS,
   CODIGO_BAR NUMBER(3) CONSTRAINT FK_ASAL_BAR REFERENCES AMCBARCOS,
   CONSTRAINT PK_ASALTAN PRIMARY KEY (CODIGO_PIR, CODIGO_BAR)
);

/*PREGUNTA 2*/

/*A*/

ALTER TABLE AMCPIRATAS ADD APODO VARCHAR2(30) CONSTRAINT APODO_UNI UNIQUE NULL;

/*B*/

ALTER TABLE AMCBARCOS DROP COLUMN TAMANO_BAR;

/*C*/

ALTER TABLE AMCASALTAN ADD FECHA_ASAL DATE;

/*D*/

ALTER TABLE AMCISLAS DROP CONSTRAINT EXT_ISL;
ALTER TABLE AMCISLAS ADD CONSTRAINT CK_ROCIO CHECK (EXTENSION BETWEEN 5000 AND 10000);

/*PREGUNTA 3*/

ALTER SESSION SET NLS_DATE_FORMAT='DD/MM/YYYY';

INSERT INTO AMCISLAS VALUES (152,'Monkey Island',6254);
INSERT INTO AMCISLAS VALUES (025,'Gran Canaria',7200);

INSERT INTO AMCPIRATAS VALUES (006,'Alberto','Moreno',NULL,025,'Patapalo');
INSERT INTO AMCPIRATAS VALUES (012,'Rodolfo','Chiquilicuatre','10/05/1972',152,'El rubio');

INSERT INTO AMCBARCOS VALUES (054,'La Perla Negra','Fragata');
INSERT INTO AMCBARCOS VALUES (089,'Toyota Corola','Goleta');

INSERT INTO AMCASALTAN VALUES (006,089,'02/05/2022');
INSERT INTO AMCASALTAN VALUES (012,054,'11/01/2023');

/*PREGUNTA 4*/

/*A*/

SELECT NOMBRE_PIR FROM AMCPIRATAS WHERE UPPER(NOMBRE_PIR) LIKE 'R%O';

/*B*/

SELECT NOMBRE_ISL FROM AMCISLAS WHERE EXTENSION BETWEEN 6000 AND 7000;

/*C*/

SELECT COUNT(TIPO_BAR) FROM AMCBARCOS WHERE TIPO_BAR = 'Goleta';

/*D*/

SELECT NOMBRE_PIR, APELLIDO_PIR FROM AMCPIRATAS WHERE FECHA_NAC IS NULL;





   
   
   