drop table fabricantes cascade constraints;
drop table articulos cascade constraints;
drop table tiendas cascade constraints;
drop table pedidos cascade constraints;
drop table ventas cascade constraints;

REM ********** TABLA FABRICANTES

CREATE TABLE FABRICANTES(
  COD_FABRICANTE NUMBER(3) CONSTRAINT PK_FA PRIMARY KEY,
  NOMBRE VARCHAR2(15) CONSTRAINT CK_NO CHECK(NOMBRE=UPPER(NOMBRE)), 
  PAIS VARCHAR2(15) CONSTRAINT CK_PA CHECK(PAIS=UPPER(PAIS)) 
);


REM **** TABLA ARTICULOS
CREATE TABLE ARTICULOS(
  ARTICULO VARCHAR2(20),
  COD_FABRICANTE NUMBER(3),
  PESO NUMBER(3) CONSTRAINT CK1_AR CHECK (PESO>0),
  CATEGORIA  VARCHAR2(10),
  PRECIO_VENTA NUMBER (4)CONSTRAINT CK2_AR CHECK (PRECIO_VENTA>0),
  PRECIO_COSTO NUMBER (4) CONSTRAINT CK3_AR CHECK (PRECIO_COSTO>0),
  EXISTENCIAS NUMBER (5),
  CONSTRAINT PK_ART PRIMARY KEY (ARTICULO, COD_FABRICANTE, PESO, CATEGORIA),
  CONSTRAINT FK_AR_FA FOREIGN KEY (COD_FABRICANTE) REFERENCES FABRICANTES,
  CONSTRAINT CK_CAT CHECK(CATEGORIA IN('Primera','Segunda', 'Tercera'))
);

REM ************* TABLA TIENDAS
CREATE TABLE TIENDAS(
  NIF VARCHAR2(10)CONSTRAINT PK_TI PRIMARY KEY,
  NOMBRE  VARCHAR2(20),
  DIRECCIÓN VARCHAR2(20),
  POBLACIÓN VARCHAR2(20),
  PROVINCIA VARCHAR2(20)CONSTRAINT CK_PRO CHECK(PROVINCIA=UPPER(PROVINCIA)), 
  CODPOSTAL NUMBER(5)
);

REM *********** TABLA PEDIDOS
CREATE TABLE PEDIDOS(
  NIF VARCHAR2(10) CONSTRAINT FK_PE_TI REFERENCES TIENDAS,
  ARTICULO VARCHAR2(20),
  COD_FABRICANTE NUMBER(3) CONSTRAINT FK_PE_FA REFERENCES FABRICANTES,
  PESO NUMBER(3),
  CATEGORIA VARCHAR2(10),
  FECHA_PEDIDO DATE,
  UNIDADES_PEDIDAS  NUMBER(4)CONSTRAINT CK_PEUP CHECK (UNIDADES_PEDIDAS>0),
  CONSTRAINT PK_PED PRIMARY KEY
       (NIF,ARTICULO, COD_FABRICANTE, PESO, CATEGORIA, FECHA_PEDIDO),
  CONSTRAINT CK_CATPE CHECK(CATEGORIA IN('Primera','Segunda','Tercera')),
  CONSTRAINT FK_PE_AR FOREIGN KEY
        (ARTICULO, COD_FABRICANTE, PESO, CATEGORIA) REFERENCES ARTICULOS
         ON DELETE CASCADE
);

REM ************* TABLA VENTAS
CREATE TABLE VENTAS(
    NIF VARCHAR2(10) CONSTRAINT FK_VE_TI REFERENCES TIENDAS,
    ARTICULO VARCHAR2(20),
    COD_FABRICANTE NUMBER(3) CONSTRAINT FK_VE_FA REFERENCES FABRICANTES,
    PESO NUMBER(3),
    CATEGORIA VARCHAR2(10) 
CONSTRAINT CK_CATVE CHECK(CATEGORIA IN('Primera','Segunda','Tercera')),
    FECHA_VENTA DATE,
    UNIDADES_VENDIDAS  NUMBER(4)
CONSTRAINT CK_VEUV CHECK (UNIDADES_VENDIDAS>0),
    CONSTRAINT PK_VEN PRIMARY KEY
      (NIF,ARTICULO, COD_FABRICANTE, PESO, CATEGORIA, FECHA_VENTA),
    CONSTRAINT FK_VEAR FOREIGN KEY
        (ARTICULO, COD_FABRICANTE, PESO, CATEGORIA) REFERENCES ARTICULOS
        ON DELETE CASCADE
);