                            
                            /*****    PARTE 1  *****/



/*****    PREGUNTA 1  *****/ /*HAY QUE PONER TODOS LOS CAMPOS NOT NULL*/


CREATE TABLE ALUMNOS (
CODIGO VARCHAR2(6) CONSTRAINT PK_ALUM PRIMARY KEY,
NIF CHAR(9) CONSTRAINT UQ_ALUM UNIQUE NOT NULL,
NOMBRE VARCHAR2(10),
APELLIDOS VARCHAR2(15),
F_NACIM DATE ,
DIRECCION VARCHAR2(25)
);

ALTER SESSION SET NLS_DATE_FORMAT = 'DD/MM/YYYY';

CREATE TABLE ASIGNATURAS (
CODIGO NUMBER(2) CONSTRAINT PK_ASIG PRIMARY KEY,
NOMBRE VARCHAR2(15),
CREDITOS NUMBER(2),
ALUMNORESPONSABLE  VARCHAR2(6) CONSTRAINT FK_AS_AL REFERENCES ALUMNOS
);

CREATE TABLE MATRICULA(
ALUMNOS VARCHAR2(6) CONSTRAINT FK_MA_AL REFERENCES ALUMNOS,
ASIGNATURA NUMBER(2) CONSTRAINT FK_MA_AS REFERENCES ASIGNATURAS,
CURSO NUMBER(4),
BECA  VARCHAR2(2)  CONSTRAINT CK_MATR  CHECK (BECA IN ('SI', 'NO')),
CONSTRAINT PK_MATR PRIMARY KEY (ALUMNOS,ASIGNATURA)
);



INSERT INTO ALUMNOS VALUES('12345A','12345678A','Nombre 1','Apellidos 1','15/12/2000', 'Dirección 1,3ºA' );
INSERT INTO ALUMNOS VALUES ('98745C','98745632C','Nombre 2','Apellidos 2','16/02/2001', 'Dirección 3,6ºB' );
commit;


INSERT INTO ASIGNATURAS VALUES (11,'Informática',20,'12345A' );
INSERT INTO ASIGNATURAS VALUES ( 12,'Matemática',15,'12345A');
INSERT INTO ASIGNATURAS VALUES (13,'Física',10,'98745C' );
commit;

INSERT INTO MATRICULA VALUES ('12345A',11,2021,'SI');
INSERT INTO MATRICULA VALUES ( '12345A',12,2022,'NO');
INSERT INTO MATRICULA VALUES ('98745C',13,2022,'NO');
commit;


/*****    PREGUNTA 2  *****/

rem añado un campo  a la tabla asignatura, por ejemplo, depende. Añadiendo una foreign key a la misma tabla asignatura("REFLEXIVA")

ALTER TABLE ASIGNATURAS 
ADD DEPENDE NUMBER(2)  CONSTRAINT FK_DEPENDE REFERENCES ASIGNATURAS;

rem se deja null porque no tiene valor 

/*****    PREGUNTA 3  *****/
rem borro las claves primarias y añadir curso a las claves primarias

ALTER TABLE MATRICULA
DROP PRIMARY KEY;

ALTER TABLE MATRICULA 
ADD CONSTRAINT PK_ASIGNATU PRIMARY KEY (ALUMNOS,ASIGNATURA,CURSO);

ALTER TABLE MATRICULA 
ADD NOTA_FINAL NUMBER(4,2);






