insert into equipo values ('Artiach','José Peréz');
insert into equipo values ('Banesto','Miguel Echevarria');
insert into equipo values ('Bresciali-Refin','Pietro Armani');
insert into equipo values ('Carrera','Luigi Petroni');
insert into equipo values ('Castorama','Jean Philip');
insert into equipo values ('Euskadi','Pedro Txucaru');
insert into equipo values ('Gatorade','Gian Luca Pacceli');
insert into equipo values ('Gewiss','Moreno Argentin');
insert into equipo values ('Jolly Club','Johan Richard');
insert into equipo values ('Kelme','Álvaro Pino');
insert into equipo values ('Lotus Festina','Suarez Cuevas');
insert into equipo values ('Mapei-Clas','Juan Fernandez');
insert into equipo values ('Mercatone Uno','Ettore Romano');
insert into equipo values ('Motorola','John Fidwell');
insert into equipo values ('Navigare','Lonrenzo Sciacci');
insert into equipo values ('ONCE','Manuel Sainz');
insert into equipo values ('PDM','Piet Van Der Kruis');
insert into equipo values ('Seguros Amaya','Minguez');
insert into equipo values ('Telecom','Morgan Reikcard');
insert into equipo values ('TVM','Steveens Henk');
insert into equipo values ('Wordperfect','Bill Gates');
insert into equipo values ('Amore Vita','Ricardo Padacci');

insert into ciclista values (1,'Miguel Indurain',32,'Banesto');
insert into ciclista values (2,'Pedro Delgado',35,'Banesto');
insert into ciclista values (3,'Alex Zulle',27,'ONCE');
insert into ciclista values (4,'Tony Rominger',30,'Mapei-Clas');
insert into ciclista values (5,'Gert-Jan Theunisse',32,'TVM');
insert into ciclista values (6,'Adriano Baffi',33,'Mercatone Uno');
insert into ciclista values (7,'Massimiliano Lelli',30,'Mercatone Uno');
insert into ciclista values (8,'Jean Van Poppel',33,'Lotus Festina');
insert into ciclista values (9,'Massimo Podenzana',34,'Navigare');
insert into ciclista values (10,'Mario Cipollini',28,'Mercatone Uno');
insert into ciclista values (11,'Flavio Giupponi',31,'Bresciali-Refin');
insert into ciclista values (12,'Alessio Di Basco',31,'Amore Vita');
insert into ciclista values (13,'Lale Cubino',28,'Seguros Amaya');
insert into ciclista values (14,'Roberto Pagnin',33,'Navigare');
insert into ciclista values (15,'Jesper Skibby',31,'TVM');
insert into ciclista values (16,'Dimitri Konishev',29,'Jolly Club');
insert into ciclista values (17,'Bruno Leali',37,'Bresciali-Refin');
insert into ciclista values (18,'Robert Millar',37,'TVM');
insert into ciclista values (19,'Julian Gorospe',34,'Banesto');
insert into ciclista values (20,'Alfonso Gutiérrez',29,'Artiach');
insert into ciclista values (21,'Erwin Nijboer',31,'Artiach');
insert into ciclista values (22,'Giorgio Furlan',32,'Gewiss');
insert into ciclista values (23,'Lance Armstrong',27,'Motorola');
insert into ciclista values (24,'Claudio Chiappucci',29,'Carrera');
insert into ciclista values (25,'Gianni Bugno',32,'Gatorade');
insert into ciclista values (26,'Mikel Zarrabeitia',27,'Banesto');
insert into ciclista values (27,'Laurent Jalabert',28,'ONCE');
insert into ciclista values (28,'Jesus Montoya',33,'Banesto');
insert into ciclista values (29,'Angel Edo',28,'Kelme');
insert into ciclista values (30,'Melchor Mauri',28,'Banesto');
insert into ciclista values (31,'Vicente Aparicio',30,'Banesto');
insert into ciclista values (32,'Laurent Dufaux',28,'ONCE');
insert into ciclista values (33,'Stefano della Santa',29,'Mapei-Clas');
insert into ciclista values (34,'Angel Yesid Camargo',30,'Kelme');
insert into ciclista values (35,'Erik Dekker',28,'Wordperfect');
insert into ciclista values (36,'Gian Matteo Fagnini',32,'Mercatone Uno');
insert into ciclista values (37,'Scott Sunderland',29,'TVM');
insert into ciclista values (38,'Javier Palacin',25,'Euskadi');
insert into ciclista values (39,'Rudy Verdonck',30,'Lotus Festina');
insert into ciclista values (40,'Viatceslav Ekimov',32,'Wordperfect');
insert into ciclista values (41,'Rolf Aldag',25,'Telecom');
insert into ciclista values (42,'Davide Cassani',29,'TVM');
insert into ciclista values (43,'Francesco Casagrande',28,'Mercatone Uno');
insert into ciclista values (44,'Luca Gelfi',27,'Gatorade');
insert into ciclista values (45,'Alberto Elli',26,'Artiach');
insert into ciclista values (46,'Agustin Sagasti',24,'Euskadi');
insert into ciclista values (47,'Laurent Pillon',32,'Gewiss');
insert into ciclista values (48,'Marco Saligari',29,'Gewiss');
insert into ciclista values (49,'Eugeni Berzin',23,'Gewiss');
insert into ciclista values (50,'Fernando Escartin',27,'Mapei-Clas');
insert into ciclista values (51,'Udo Bolts',30,'Telecom');
insert into ciclista values (52,'Vladislav Bobrik',26,'Gewiss');
insert into ciclista values (53,'Michele Bartoli',28,'Mercatone Uno');
insert into ciclista values (54,'Steffen Wesemann',30,'Telecom');
insert into ciclista values (55,'Nicola Minali',28,'Gewiss');
insert into ciclista values (56,'Andrew Hampsten',29,'Banesto');
insert into ciclista values (57,'Stefano Zanini',28,'Navigare');
insert into ciclista values (58,'Gerd Audehm',34,'Telecom');
insert into ciclista values (59,'Mariano Picolli',28,'Mercatone Uno');
insert into ciclista values (60,'Giovanni Lombardi',28,'Bresciali-Refin');
insert into ciclista values (61,'Walte Castignola',26,'Navigare');
insert into ciclista values (62,'Raul Alcala',30,'Motorola');
insert into ciclista values (63,'Alvaro Mejia',32,'Motorola');
insert into ciclista values (64,'Giuseppe Petito',28,'Mercatone Uno');
insert into ciclista values (65,'Pascal Lino',29,'Amore Vita');
insert into ciclista values (66,'Enrico Zaina',24,'Gewiss');
insert into ciclista values (67,'Armand de las Cuevas',28,'Castorama');
insert into ciclista values (68,'Angel Citracca',28,'Navigare');
insert into ciclista values (69,'Eddy Seigneur',27,'Castorama');
insert into ciclista values (70,'Sandro Heulot',29,'Banesto');
insert into ciclista values (71,'Prudencio Indur?in',27,'Banesto');
insert into ciclista values (72,'Stefano Colage',28,'Bresciali-Refin');
insert into ciclista values (73,'Laurent Fignon',35,'Gatorade');
insert into ciclista values (74,'Claudio Chioccioli',36,'Amore Vita');
insert into ciclista values (75,'Juan Romero',32,'Seguros Amaya');
insert into ciclista values (76,'Marco Giovannetti',34,'Gatorade');
insert into ciclista values (77,'Javier Mauleon',33,'Mapei-Clas');
insert into ciclista values (78,'Antonio Esparza',35,'Kelme');
insert into ciclista values (79,'Johan Bruyneel',33,'ONCE');
insert into ciclista values (80,'Federico Echave',37,'Mapei-Clas');
insert into ciclista values (81,'Piotr Ugrumov',33,'Gewiss');
insert into ciclista values (82,'Edgar Corredor',30,'Kelme');
insert into ciclista values (83,'Hernan Buenahora',32,'Kelme');
insert into ciclista values (84,'Jon Unzaga',31,'Mapei-Clas');
insert into ciclista values (85,'Dimitri Abdoujaparov',30,'Carrera');
insert into ciclista values (86,'Juan Martinez Oliver',32,'Kelme');
insert into ciclista values (87,'Fernando Mota',32,'Artiach');
insert into ciclista values (88,'Angel Camarillo',28,'Mapei-Clas');
insert into ciclista values (89,'Stefan Roche',36,'Carrera');
insert into ciclista values (90,'Ivan Ivanov',27,'Artiach');
insert into ciclista values (91,'Nestor Mora',28,'Kelme');
insert into ciclista values (92,'Federico Garcia',27,'Artiach');
insert into ciclista values (93,'Bo Hamburger',29,'TVM');
insert into ciclista values (94,'Marino Alonso',30,'Banesto');
insert into ciclista values (95,'Manuel Guijarro',31,'Lotus Festina');
insert into ciclista values (96,'Tom Cordes',29,'Wordperfect');
insert into ciclista values (97,'Casimiro Moreda',28,'ONCE');
insert into ciclista values (98,'Eleuterio Anguita',25,'Artiach');
insert into ciclista values (99,'Per Pedersen',29,'Seguros Amaya');
insert into ciclista values (100,'William Palacios',30,'Jolly Club');
commit;





