

CREATE TABLE UPERSONA
(
  NIF CHAR(9),
  NOMBRE VARCHAR2(25) NOT NULL,
  APELLIDO VARCHAR2(50) NOT NULL,
  CIUDAD VARCHAR2(25),
  DIRECCIONCALLE VARCHAR2(50),
  DIRECCIONNUM CHAR(3),
  TELEFONO CHAR(9),
  FECHANACIMIENTO DATE,
  VARON CHAR(1),
  CONSTRAINT PK_UPERSONA PRIMARY KEY(NIF),
  CONSTRAINT CK_VARON CHECK  (VARON IN ('0','1'))
 );



CREATE TABLE UPROFESOR
(
  IDPROFESOR CHAR(4),
  NIF CHAR(9),
  CONSTRAINT PK_UPROF PRIMARY KEY(IDPROFESOR),
  CONSTRAINT FK_UPROF_PER FOREIGN KEY(NIF) REFERENCES UPERSONA
); 



CREATE TABLE UALUMNO
(
  IDALUMNO CHAR(7),
  NIF CHAR(9),
  CONSTRAINT PK_UALUM PRIMARY KEY(IDALUMNO),
  CONSTRAINT FK_UALUM_PER FOREIGN KEY(NIF) REFERENCES UPERSONA
); 



CREATE TABLE UTITULACION
(
  IDTITULACION CHAR(6),
  NOMBRE VARCHAR2 (20) NOT NULL,
  CONSTRAINT PK_UTITUL PRIMARY KEY(IDTITULACION),
  CONSTRAINT CK_NOM UNIQUE(NOMBRE) 
 );
  

CREATE TABLE UASIGNATURA
(
 IDASIGNATURA CHAR(6),
 NOMBRE VARCHAR2(50) NOT NULL,
 CREDITOS NUMBER,
 CUATRIMESTRE CHAR(1),
 COSTEBASICO NUMBER(5,2),
 IDPROFESOR CHAR(4),
 IDTITULACION CHAR(6),
 CURSO CHAR(1),
 CONSTRAINT PK_UASIG PRIMARY KEY (IDASIGNATURA),
 CONSTRAINT CK_CRED CHECK (CREDITOS IN ('4.5','6','7.5','9')),
 CONSTRAINT CK_CUATR CHECK(CUATRIMESTRE IN ('1','2')),
 CONSTRAINT FK_UASIG_PROF FOREIGN KEY (IDPROFESOR) REFERENCES UPROFESOR,
 CONSTRAINT FK_UASIG_TIT FOREIGN KEY(IDTITULACION) REFERENCES UTITULACION,
 CONSTRAINT CK_CURSO CHECK(CURSO IN('1','2','3','4'))
);


CREATE TABLE UALUMNO_UASIGNATURA
(
  IDALUMNO CHAR(7),
  IDASIGNATURA CHAR(6),
  NUMEROMATRICULA NUMBER(1) NOT NULL,
  CONSTRAINT PK_MATRIC PRIMARY KEY (IDALUMNO,IDASIGNATURA),
  CONSTRAINT FK_UALUM FOREIGN KEY(IDALUMNO) REFERENCES UALUMNO,
  CONSTRAINT FK_ASIG FOREIGN KEY(IDASIGNATURA) REFERENCES UASIGNATURA,
  CONSTRAINT CK_MATRIC CHECK(NUMEROMATRICULA>=1 AND NUMEROMATRICULA<=6)
 );



