INSERT INTO ESTACION VALUES(1,'CARTUJA','C1');
INSERT INTO ESTACION VALUES(2,'BARQUETA','B1');
INSERT INTO ESTACION VALUES(3,'MACARENA','M1');
INSERT INTO ESTACION VALUES(4,'OSARIO','O1');
INSERT INTO ESTACION VALUES(5,'SANTA JUSTA','S1');
INSERT INTO ESTACION VALUES(6,'RAMON Y CAJAL','R1');
INSERT INTO ESTACION VALUES(7,'PASARELA','P1');
INSERT INTO ESTACION VALUES(8,'VIRGEN DE LUJAN','V1');
INSERT INTO ESTACION VALUES(9,'RONDA DE TRIANA','R2');
INSERT INTO ESTACION VALUES(10,'SAN JACINTO','S2');
INSERT INTO ESTACION VALUES(11,'RONDA DE CAPUCHINO','R3');
INSERT INTO ESTACION VALUES(12,'GUADAIRA','G2');
INSERT INTO ESTACION VALUES(13,'CIUDAD SANITARIA','C2');
INSERT INTO ESTACION VALUES(14,'PRADO','P2');
INSERT INTO ESTACION VALUES(15,'POLIGONO NORTE','P3');
INSERT INTO ESTACION VALUES(16,'HELIOPOLIS','H1');
INSERT INTO ESTACION VALUES(17,'RONDA TAMARGUILLO','R4');

INSERT INTO LINEA VALUES(1,'C1','CIRCULAR');
INSERT INTO LINEA VALUES(2,'C2','CIRCULAR');
INSERT INTO LINEA VALUES(3,'C3','CENTRO');
INSERT INTO LINEA VALUES(4,'C4','EXTRARADIOS');
INSERT INTO LINEA VALUES(5,'C5','CENTRO');


INSERT INTO ACCESO VALUES(1,'N',1);
INSERT INTO ACCESO VALUES(2,'S',1);
INSERT INTO ACCESO VALUES(3,'E',1);
INSERT INTO ACCESO VALUES(4,'O',1);
INSERT INTO ACCESO VALUES(5,'N',2);
INSERT INTO ACCESO VALUES(6,'S',2);
INSERT INTO ACCESO VALUES(7,'E',2);
INSERT INTO ACCESO VALUES(8,'O',2);
INSERT INTO ACCESO VALUES(9,'N',3);
INSERT INTO ACCESO VALUES(10,'S',3);
INSERT INTO ACCESO VALUES(11,'O',3);
INSERT INTO ACCESO VALUES(12,'N',4);
INSERT INTO ACCESO VALUES(13,'S',4);
INSERT INTO ACCESO VALUES(14,'E',4);
INSERT INTO ACCESO VALUES(15,'O',4);
INSERT INTO ACCESO VALUES(16,'N',5);
INSERT INTO ACCESO VALUES(17,'N',6);
INSERT INTO ACCESO VALUES(18,'S',7);
INSERT INTO ACCESO VALUES(19,'N',8);
INSERT INTO ACCESO VALUES(20,'S',9);
INSERT INTO ACCESO VALUES(21,'N',10);
INSERT INTO ACCESO VALUES(22,'S',11);
INSERT INTO ACCESO VALUES(23,'N',12);
INSERT INTO ACCESO VALUES(24,'S',13);
INSERT INTO ACCESO VALUES(25,'N',14);
INSERT INTO ACCESO VALUES(26,'S',15);
INSERT INTO ACCESO VALUES(27,'N',16);

INSERT INTO LINEA_ESTACION VALUES (1,1,1);
INSERT INTO LINEA_ESTACION VALUES (1,2,2);
INSERT INTO LINEA_ESTACION VALUES (1,3,3);
INSERT INTO LINEA_ESTACION VALUES (1,4,4);
INSERT INTO LINEA_ESTACION VALUES (1,5,5);
INSERT INTO LINEA_ESTACION VALUES (1,6,6);
INSERT INTO LINEA_ESTACION VALUES (1,7,7);
INSERT INTO LINEA_ESTACION VALUES (1,8,8);
INSERT INTO LINEA_ESTACION VALUES (1,9,9);
INSERT INTO LINEA_ESTACION VALUES (1,1,10);
INSERT INTO LINEA_ESTACION VALUES (2,1,10);
INSERT INTO LINEA_ESTACION VALUES (2,2,9);
INSERT INTO LINEA_ESTACION VALUES (2,3,8);
INSERT INTO LINEA_ESTACION VALUES (2,4,7);
INSERT INTO LINEA_ESTACION VALUES (2,5,6);
INSERT INTO LINEA_ESTACION VALUES (2,6,5);
INSERT INTO LINEA_ESTACION VALUES (2,7,4);
INSERT INTO LINEA_ESTACION VALUES (2,8,3);
INSERT INTO LINEA_ESTACION VALUES (2,9,2);
INSERT INTO LINEA_ESTACION VALUES (2,1,1);
INSERT INTO LINEA_ESTACION VALUES (3,10,1);
INSERT INTO LINEA_ESTACION VALUES (3,3,2);
INSERT INTO LINEA_ESTACION VALUES (3,11,3);
INSERT INTO LINEA_ESTACION VALUES (3,7,4);
INSERT INTO LINEA_ESTACION VALUES (3,10,5);
INSERT INTO LINEA_ESTACION VALUES (4,12,5);
INSERT INTO LINEA_ESTACION VALUES (4,13,4);
INSERT INTO LINEA_ESTACION VALUES (4,14,3);
INSERT INTO LINEA_ESTACION VALUES (4,4,2);
INSERT INTO LINEA_ESTACION VALUES (4,15,1);
INSERT INTO LINEA_ESTACION VALUES (5,16,1);
INSERT INTO LINEA_ESTACION VALUES (5,13,2);
INSERT INTO LINEA_ESTACION VALUES (5,11,3);

INSERT INTO COCHERA VALUES(1,'B1',1,4);
INSERT INTO COCHERA VALUES(2,'B2',1,2);
INSERT INTO COCHERA VALUES(3,'A1',2,4);
INSERT INTO COCHERA VALUES(4,'A2',2,4);
INSERT INTO COCHERA VALUES(5,'A3',2,2);
INSERT INTO COCHERA VALUES(6,'A4',3,2);
INSERT INTO COCHERA VALUES(7,'A5',3,2);
INSERT INTO COCHERA VALUES(8,'A6',4,6);
INSERT INTO COCHERA VALUES(9,'A7',4,6);
INSERT INTO COCHERA VALUES(10,'A8',4,6);
INSERT INTO COCHERA VALUES(11,'A9',5,2);
INSERT INTO COCHERA VALUES(12,'A10',5,2);
INSERT INTO COCHERA VALUES(13,'A11',6,2);
INSERT INTO COCHERA VALUES(14,'A12',6,2);
INSERT INTO COCHERA VALUES(15,'A13',7,2);
INSERT INTO COCHERA VALUES(16,'A14',7,2);
INSERT INTO COCHERA VALUES(17,'A15',8,6);
INSERT INTO COCHERA VALUES(18,'A16',8,6);
INSERT INTO COCHERA VALUES(19,'A17',8,6);
INSERT INTO COCHERA VALUES(20,'A18',8,6);
INSERT INTO COCHERA VALUES(21,'A19',9,2);
INSERT INTO COCHERA VALUES(22,'A20',9,2);
INSERT INTO COCHERA VALUES(23,'A21',10,2);
INSERT INTO COCHERA VALUES(24,'A22',10,2);


INSERT INTO TREN VALUES (1,'MODELO 1',100,SYSDATE,1,1);
INSERT INTO TREN VALUES (2,'MODELO 1',100,SYSDATE,1,1);
INSERT INTO TREN VALUES (3,'MODELO 1',100,SYSDATE,1,1);
INSERT INTO TREN VALUES (4,'MODELO 1',100,SYSDATE,2,1);
INSERT INTO TREN VALUES (5,'MODELO 1',100,SYSDATE,2,1);
INSERT INTO TREN VALUES (6,'MODELO 1',80,SYSDATE,3,1);
INSERT INTO TREN VALUES (7,'MODELO 1',80,SYSDATE,3,1);
INSERT INTO TREN VALUES (8,'MODELO 1',80,SYSDATE,3,1);
INSERT INTO TREN VALUES (9,'MODELO 1',80,SYSDATE,3,1);
INSERT INTO TREN VALUES (10,'MODELO 1',80,SYSDATE,4,1);
INSERT INTO TREN VALUES (11,'MODELO 1',80,SYSDATE,4,1);
INSERT INTO TREN VALUES (12,'MODELO 1',100,SYSDATE,4,1);
INSERT INTO TREN VALUES (13,'MODELO 1',90,SYSDATE,4,2);
INSERT INTO TREN VALUES (14,'MODELO 1',90,SYSDATE,5,2);
INSERT INTO TREN VALUES (15,'MODELO 1',90,SYSDATE,5,2);
INSERT INTO TREN VALUES (16,'MODELO 1',80,SYSDATE,6,2);
INSERT INTO TREN VALUES (17,'MODELO 1',80,SYSDATE,6,2);
INSERT INTO TREN VALUES (18,'MODELO 1',90,SYSDATE,7,2);
INSERT INTO TREN VALUES (19,'MODELO 1',100,SYSDATE,7,2);
INSERT INTO TREN VALUES (20,'MODELO 1',90,SYSDATE,8,2);
INSERT INTO TREN VALUES (21,'MODELO 1',80,SYSDATE,8,2);
INSERT INTO TREN VALUES (22,'MODELO 1',80,SYSDATE,8,2);
INSERT INTO TREN VALUES (23,'MODELO 1',80,SYSDATE,8,2);
INSERT INTO TREN VALUES (24,'MODELO 1',80,SYSDATE,9,3);
INSERT INTO TREN VALUES (25,'MODELO 1',90,SYSDATE,9,3);
INSERT INTO TREN VALUES (26,'MODELO 1',90,SYSDATE,9,3);
INSERT INTO TREN VALUES (27,'MODELO 1',80,SYSDATE,9,3);
INSERT INTO TREN VALUES (28,'MODELO 1',80,SYSDATE,10,3);
INSERT INTO TREN VALUES (29,'MODELO 1',80,SYSDATE,10,3);
INSERT INTO TREN VALUES (30,'MODELO 1',80,SYSDATE,10,4);
INSERT INTO TREN VALUES (31,'MODELO 1',90,SYSDATE,10,4);
INSERT INTO TREN VALUES (32,'MODELO 1',80,SYSDATE,10,4);
INSERT INTO TREN VALUES (33,'MODELO 1',80,SYSDATE,11,4);
INSERT INTO TREN VALUES (34,'MODELO 1',80,SYSDATE,11,4);
INSERT INTO TREN VALUES (35,'MODELO 1',90,SYSDATE,12,4);
INSERT INTO TREN VALUES (36,'MODELO 1',90,SYSDATE,12,4);
INSERT INTO TREN VALUES (37,'MODELO 1',80,SYSDATE,13,4);
INSERT INTO TREN VALUES (38,'MODELO 1',80,SYSDATE,13,4);
INSERT INTO TREN VALUES (39,'MODELO 1',80,SYSDATE,14,5);
INSERT INTO TREN VALUES (40,'MODELO 1',80,SYSDATE,14,5);
INSERT INTO TREN VALUES (41,'MODELO 1',90,SYSDATE,15,5);

COMMIT;
/**************/

/*1.- Obtén los datos de todas las estaciones que tienen orientación “Norte” en alguno de
sus accesos y lque a localización de su cochera empiece por “A” ;*/

select * from estacion where codigo IN 
(select estacion from acceso 
where orientacion='N') and codigo IN (select estacion from cochera where localizacion like 'A%');

select distinct e.* from estacion e, acceso a, cochera c
where e.codigo=a.estacion and e.codigo=c.estacion
and upper(orientacion)='N' and upper(localizacion) like 'A%';
/*2.- Muestra la localización de las cocheras junto con la cantidad de los distintos
modelos de tren que tiene.*/

select c.localizacion, count(distinct (modelo)) from cochera c, tren t
where t.cochera=c.codigo group by localizacion;
 
/*3.- Crea una tabla llamada “tabla3” que contenga las parejas de nombre de estación que
están en el mismo distrito. También ha de salir el nombre del distrito.*/

create table table3 (nombre1, nombre2, distrito) as select est1.nombre, est2.nombre, est1.distrito
from estacion est1, estacion est2 where est1.distrito=est2.distrito and est1.codigo>est2.codigo;
 
/*4.- Realiza los siguientes apartados
a) Inserta un tren con el código 42, la fecha de entrada es la del sistema y los
campos cochera y línea coincida con el tren de código 10.*/
insert into tren (codigo, modelo, fecha_entrada, cochera, linea)
select 42,modelo,sysdate,cochera,linea from tren where codigo=10;

/*b) Actualiza la relación tren para que la tupla añadida en el apartado anterior (tren
con código 42) tenga el campo velocidad_máxima con la velocidad media de
todos los trenes.*/

UPDATE TREN
SET VELOCIDAD_MAXIMA = (SELECT ROUND(AVG(VELOCIDAD_MAXIMA), 0) FROM TREN)
WHERE CODIGO = 42;
commit;

/*5.- Realiza los siguientes apartados
a) Inserta una línea con código: “6”, nombre: “C6” y cobertura: “Extrarradios”*/

INSERT INTO LINEA VALUES (6, 'C6', 'EXTRARADIOS');
commit;

/*b) Crea una tabla llamada “tabla5” que muestre el nombre de la línea, su cobertura
y el no de estaciones por las que pasa. Si no pasa por ninguna estación tiene que
salir 0.*/

CREATE TABLE TABLE5 AS SELECT L.NOMBRE, L.COBERTURA, COUNT(LE.ESTACION) AS NUMERO_ESTACIONES
FROM LINEA L, LINEA_ESTACION LE WHERE L.CODIGO = LE.LINEA(+) GROUP BY L.NOMBRE, L.COBERTURA

/*6.- Refleja en el sistema que la estación de “Santa Justa”, tiene un nuevo acceso con
orientación “Este”. El numero de acceso es una unidad mas con respecto al mayor que
hay introducido.
Nota: hay que insertar en la tabla acceso*/

INSERT INTO ACCESO SELECT NUMERO_ACCESO+1,'E',
(SELECT CODIGO FROM ESTACION WHERE UPPER(NOMBRE)='SANTA JUSTA')
FROM ACCESO
WHERE NUMERO_ACCESO= (SELECT MAX(NUMERO_ACCESO)FROM ACCESO);

/*7.- Todas las cocheras que tienen estaciones con líneas con la cobertura “Centro” pasa a
tener la misma capacidad y localización que la cochera con código 8*/

UPDATE COCHERA
SET CAPACIDAD = (SELECT CAPACIDAD FROM COCHERA WHERE CODIGO = 8),
LOCALIZACION = (SELECT LOCALIZACION FROM COCHERA WHERE CODIGO = 8)
WHERE ESTACION IN (SELECT DISTINCT ESTACION FROM LINEA_ESTACION WHERE LINEA IN 
(SELECT CODIGO FROM LINEA WHERE COBERTURA = 'CENTRO'));

UPDATE COCHERA SET (LOCALIZACION,CAPACIDAD) =
(SELECT LOCALIZACION, CAPACIDAD FROM COCHERA WHERE CODIGO=8)
WHERE ESTACION IN
(SELECT DISTINCT ESTACION FROM LINEA_ESTACION LE, LINEA L
WHERE LE.LINEA=L.CODIGO AND UPPER(COBERTURA)='CENTRO');

/*8.- Aumenta en 5 km la velocidad de todos los trenes que tengan el mismo modelo y
velocidad que el tren con codigo “17” (al tren 17 no hay que aumentarle los km)*/

UPDATE TREN
SET VELOCIDAD_MAXIMA = VELOCIDAD_MAXIMA + 5
WHERE MODELO = (SELECT MODELO FROM TREN WHERE CODIGO = 17)
AND VELOCIDAD_MAXIMA = (SELECT VELOCIDAD_MAXIMA FROM TREN WHERE CODIGO = 17)
AND CODIGO != 17;

UPDATE TREN
SET VELOCIDAD_MAXIMA = VELOCIDAD_MAXIMA + 5
WHERE (MODELO, VELOCIDAD_MAXIMA)=(SELECT MODELO, VELOCIDAD_MAXIMA FROM TREN WHERE CODIGO= 17)
AND CODIGO !=17;

/*9.- Da de baja en el sistema a la lineas de “Extrarradios”. Pero antes asigna sus trenes a
la línea “Circular” (C).
Ten en cuenta que también tienes que “¿borrar o modificar ?” los datos de linea
estación*/

UPDATE TREN
SET LINEA = (SELECT CODIGO FROM LINEA WHERE NOMBRE = 'CIRCULAR')
WHERE LINEA IN (SELECT CODIGO FROM LINEA WHERE COBERTURA = 'EXTRARADIOS');

DELETE FROM LINEA_ESTACION
WHERE LINEA IN (SELECT CODIGO FROM LINEA WHERE COBERTURA = 'EXTRARADIOS');

DELETE FROM LINEA
WHERE COBERTURA = 'EXTRARADIOS';
