drop table estacion cascade constraints;
drop table linea cascade constraints;
drop table acceso cascade constraints;
drop table cochera cascade constraints;
drop table tren cascade constraints;
drop table linea_estacion cascade constraints;




CREATE TABLE ESTACION
(
CODIGO NUMBER(3) CONSTRAINT PK_ESTACION PRIMARY KEY,
NOMBRE VARCHAR2(20) CONSTRAINT U_ESTACION UNIQUE,
DISTRITO VARCHAR2(10)
);

CREATE TABLE LINEA
(
CODIGO NUMBER(3),
NOMBRE VARCHAR2(20) CONSTRAINT U_LINEA UNIQUE,
COBERTURA VARCHAR (12),
CONSTRAINT PK_LINEA PRIMARY KEY  (CODIGO),
CONSTRAINT CK_L_COBERTURA CHECK(COBERTURA IN ('CIRCULAR','CENTRO', 'EXTRARADIOS'))
);

CREATE TABLE ACCESO
(
NUMERO_ACCESO NUMBER(3),
ORIENTACION CHAR(1),
ESTACION NUMBER(3),
CONSTRAINT CK_L_ORIENTACION CHECK(ORIENTACION IN ('N','O','E','S')),
CONSTRAINT PK_ACCESO PRIMARY KEY (NUMERO_ACCESO),
CONSTRAINT FK_ACCESO FOREIGN KEY (ESTACION) REFERENCES ESTACION
);

CREATE TABLE COCHERA
(
CODIGO NUMBER(3),
LOCALIZACION VARCHAR2(12),
ESTACION NUMBER(3),
CAPACIDAD NUMBER(3),
CONSTRAINT PK_COCHERA PRIMARY KEY(CODIGO),
CONSTRAINT FK_COCHERA FOREIGN KEY (ESTACION) REFERENCES ESTACION
);

CREATE TABLE TREN
(
CODIGO NUMBER(3),
MODELO VARCHAR2(12),
VELOCIDAD_MAXIMA NUMBER(3),
FECHA_ENTRADA DATE,
COCHERA	NUMBER(3),
LINEA NUMBER(3),
CONSTRAINT PK_TREN PRIMARY KEY (CODIGO),
CONSTRAINT FK_T_COCHERA	FOREIGN KEY (COCHERA) REFERENCES COCHERA,
CONSTRAINT FK_T_LINEA FOREIGN KEY (LINEA) REFERENCES LINEA
);

CREATE TABLE LINEA_ESTACION 
(LINEA NUMBER(3),  
ESTACION NUMBER(3), 
NUMERO_ORDEN NUMBER(3),
CONSTRAINT PK_L_E PRIMARY KEY (LINEA,ESTACION,NUMERO_ORDEN),
CONSTRAINT FK_L_E_1 FOREIGN KEY (LINEA) REFERENCES LINEA,
CONSTRAINT FK_L_E_2	FOREIGN KEY (ESTACION) REFERENCES ESTACION
);






